server:
  port: 8080
spring:
  application:
    name: CLIENT
  http:
    encoding:
      force: true
      charset: UTF-8
  datasource:
    url: jdbc:mysql://toanyone.cb8zbp7kmosr.ap-northeast-2.rds.amazonaws.com:3306/toanyone
    username: toanyone_master
    password: 72001827
    driverClassName: com.mysql.jdbc.Driver
  jpa:
    showSql: true
    hibernate:
      ddlAuto: update
      namingStrategy: org.hibernate.cfg.ImprovedNamingStrategy
      formatSql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        formatSql: true
        id:
          newGeneratorMappings: true
  zipkin:
    baseUrl: http://ip-172-31-12-174.ap-northeast-2.compute.internal:9411
  sleuth:
    sampler:
      percentage: 0.2
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: false
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
endpoints:
  shutdown:
    enabled: true
    sensitive: false
---
spring:
  profiles: prd
logging:
  config: classpath:logback-prd.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://ip-172-31-13-153.ap-northeast-2.compute.internal:8761/eureka/

---
spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: ide
logging:
  config: classpath:logback-ide.xml
eureka:
  client:
    serviceUrl:
      defaultZone: http://ec2-13-125-21-72.ap-northeast-2.compute.amazonaws.com:8761/eureka/